# All keys

KEYS = [
    "INDIVIDUAL OR RECEIVING COMPANY NAME",
    "SWEEP TRANSFR FROM INVESTMENT ACCT",
    "RECEIVER FINANCIAL INSTITUTION ID",
    "SENDER FINANCIAL INSTITUTION ID",
    "INSTRUCTION FOR CREDITOR AGENT",
    "COMPANY DISCRETIONARY DATA",
    "SWEEP TO INVESTMENT ACCT",
    "INITIATING PARTY ORG ID",
    "ADDITIONAL INFORMATION",
    "REMITTANCE INFORMATION",
    "ACCOUNT TRANSFER FROM",
    "ACTUAL DEPOSIT AMOUNT",
    "ORIGINATING BANK NAME",
    "DAILY INTEREST SWEEP",
    "EFFECTIVE ENTRY DATE",
    "ITEM SEQUENCE NUMBER",
    "ACCOUNT TRANSFER TO",
    "DATE/TIME COMPLETED",
    "FDMS-SETTLEMENT FEE",
    "MERCHANT CHARGEBACK",
    "DATE/TIME RECEIVED",
    "DISCRETIONARY DATA",
    "MERCHANT INTERCHNG",
    "TRANSACTION REF NO",
    "Transaction Ref No",
    "CORRECTION REASON",
    "ENTRY DESCRIPTION",
    "INSTRUCTED AMOUNT",
    "INSTRUCTING AGENT",
    "MERCHANT DISCOUNT",
    "RECEIVER ACCT NUM",
    "SENDERS REFERENCE",
    "STANDBY L/C DEBIT",
    "BANK DESCRIPTION",
    "INSTRUCTED AGENT",
    "MERCHANT DEPOSIT",
    "ORIGINATING BANK",
    "RECEIVER ABA NUM",
    "RECEIVER ACCOUNT",
    "RECEIVER ADDRESS",
    "TRANSACTION CODE",
    "ADVANCE DEPOSIT",
    "CHARGING OPTION",
    "EXCHANGE AMOUNT",
    "FULL REFERENCE#",
    "PAYMENT DETAILS",
    "SENDER BANK REF",
    "SENDING CO NAME",
    "TRANSACTION REF",
    "BANK TRACE NUM",
    "CONTROL NUMBER",
    "CREDITOR AGENT",
    "EFFECTIVE DATE",
    "FULL REFERENCE",
    "RECEIVING BANK",
    "REMOTE CAPTURE",
    "SENDER ACCOUNT",
    "SENDER ADDRESS",
    "SUBSTITUTE CHK",
    "SWEEP INTEREST",
    "CO DISCR DATA",
    "CURRENCY DESC",
    "CUSTOMER NAME",
    "EXCHANGE RATE",
    "IMAGE DEPOSIT",
    "INDIVIDUAL ID",
    "ORIG BANK ABA",
    "Ordering Bank",
    "Ordering Cust",
    "RECEIVER NAME",
    "REMIT DETAILS",
    "RETURN REASON",
    "WIRE CURRENCY",
    "B/O CUSTOMER",
    "CASHED CHECK",
    "COMPANY DATA",
    "COMPANY NAME",
    "CREDITOR REF",
    "DEBTOR AGENT",
    "DEPOSIT DATE",
    "DISBURSEMENT",
    "ENTRY DESC R",
    "INITIATED BY",
    "MAIL DEPOSIT",
    "MERCHANT FEE",
    "NJ LOAN PMTS",
    "ORIG CO NAME",
    "PAYMENT DATE",
    "PAYMENT/PURP",
    "Payment Type",
    "REC BANK ABA",
    "REMIT METHOD",
    "SRFCUST NAME",
    "TRACE NUMBER",
    "ACCT NUMBER",
    "APPROVED BY",
    "BATCH DISCR",
    "BENEFICIARY",
    "COMM CHARGE",
    "DESCRIPTION",
    "DR BANK REF",
    "DR CUST REF",
    "DR TRANS ID",
    "Description",
    "ENTRY CLASS",
    "ENTRY DESCR",
    "FEES LIFTED",
    "FX CURRENCY",
    "NJ FEE PMTS",
    "ORG DEP AMT",
    "RECEIVED AT",
    "RELATED REF",
    "SENDER NAME",
    "SERVICE REF",
    "WIRE AMOUNT",
    "ACCT PARTY",
    "BNF STREET",
    "BNK STREET",
    "CLASS CODE",
    "COMPANY ID",
    "CR ADDRESS",
    "CR BANK ID",
    "DR BANK ID",
    "ENTRY DATE",
    "FED REF NO",
    "Fed Ref No",
    "IND I D NO",
    "ITEM TRACE",
    "MISC DEBIT",
    "ORG STREET",
    "ORIG BA NK",
    "ORIGINATOR",
    "PAR NUMBER",
    "PARTIALREF",
    "RECV ID NO",
    "RETURN REF",
    "SENDER REF",
    "TRANS TYPE",
    "USD AMOUNT",
    "VALUE DATE",
    "ACC PARTY",
    "CHECK NUM",
    "COMP NAME",
    "CUST NAME",
    "DATE/TIME",
    "DEBIT REF",
    "DESC DATE",
    "FILE NAME",
    "FROM ACCT",
    "IND ID NO",
    "INSTG BNK",
    "LISTED AS",
    "ORIG BANK",
    "RECV NAME",
    "RECVID NO",
    "REFERENCE",
    "RMT USTRD",
    "Reference",
    "SENDER AC",
    "SHIP DATE",
    "SHOULD BE",
    "SWIFT REF",
    "TRACE NUM",
    "ULTI BENE",
    "WIRE TYPE",
    "B/O BANK",
    "BATCH ID",
    "CHECK NO",
    "CHIP REF",
    "CHIP SEQ",
    "CREDITOR",
    "CUST RRN",
    "FED IMAD",
    "IND NAME",
    "REC BANK",
    "REC FROM",
    "REC G FP",
    "SEC CODE",
    "SNDR REF",
    "TRACE NO",
    "YOUR REF",
    "ACCOUNT",
    "ADDENDA",
    "AMT/CUR",
    "BANK ID",
    "BENEBNK",
    "COMP ID",
    "CONFIRM",
    "CR ACCT",
    "CR NAME",
    "CREATED",
    "CUST ID",
    "DEP AMT",
    "DEPDATE",
    "DEPOSIT",
    "DR ACCT",
    "DR NAME",
    "FED REF",
    "INVOICE",
    "LBX DEP",
    "MRN SEQ",
    "ORG BNK",
    "ORIG ID",
    "ORIGIN#",
    "PAID TO",
    "R EMARK",
    "REC GFP",
    "RECV BK",
    "RECVBNK",
    "REMA RK",
    "REMAR K",
    "SENT AT",
    "SND BNK",
    "AMOUNT",
    "BNF BK",
    "Branch",
    "CO EFF",
    "CR BNK",
    "DB BNK",
    "DEBTOR",
    "DR BNK",
    "FED ID",
    "INS BK",
    "INT BK",
    "ORG BK",
    "ORG ID",
    "ORIGIN",
    "REASON",
    "REF NO",
    "REMARK",
    "SND BK",
    "SOURCE",
    "AS OF",
    "CHECK",
    "PAYER",
    "VLTID",
    "ACCT",
    "ADDR",
    "BN F",
    "CTRY",
    "DATE",
    "DESC",
    "IMAD",
    "INFO",
    "ORIG",
    "PLAN",
    "RATE",
    "S AC",
    "SETT",
    "TIME",
    "TYPE",
    "UETR",
    "ULID",
    "ABA",
    "ADV",
    "BAG",
    "BBI",
    "BBK",
    "BIC",
    "BLK",
    "BNF",
    "CHG",
    "CTY",
    "DOB",
    "IBK",
    "INS",
    "LTN",
    "OBI",
    "OBK",
    "OGB",
    "ORF",
    "ORG",
    "POB",
    "QID",
    "REF",
    "RFB",
    "SBK",
    "SBR",
    "SEC",
    "SRC",
    "SRF",
    "TCN",
    "TRN",
    "TTM",
    "TYP",
    "BC",
]


INLINE_KEYS = ["ID","PURPOSE CODE","PURPOSE","AC","BC"]

if __name__=='__main__':
    
    print(sorted(KEYS,key=len,reverse=True))
    pass