# ACH Keys
KEYS = [
    "INDIVIDUAL OR RECEIVING COMPANY NAME",
    "ORIGINATING BANK NAME",
    "EFFECTIVE ENTRY DATE",
    "DISCRETIONARY DATA",
    "TRANSACTION REF NO",
    "ENTRY DESCRIPTION",
    "RECEIVER ACCT NUM",
    "RECEIVER ABA NUM",
    "TRANSACTION CODE",
    "SENDING CO NAME",
    "TRANSACTION REF",
    "BANK TRACE NUM",
    "EFFECTIVE DATE",
    "CO DISCR DATA",
    "CUSTOMER NAME",
    "INDIVIDUAL ID",
    "RECEIVER NAME",
    "RETURN REASON",
    "COMPANY DATA",
    "COMPANY NAME",
    "ENTRY DESC R",
    "ORIG CO NAME",
    "TRACE NUMBER",
    "BATCH DISCR",
    "DESCRIPTION",
    "ENTRY CLASS",
    "ENTRY DESCR",
    "CLASS CODE",
    "COMPANY ID",
    "ENTRY DATE",
    "FED REF NO",
    "IND I D NO",
    "ITEM TRACE",
    "ORIG BA NK",
    "RECV ID NO",
    "RETURN REF",
    "TRANS TYPE",
    "COMP NAME",
    "CUST NAME",
    "DESC DATE",
    "FILE NAME",
    "IND ID NO",
    "ORIG BANK",
    "RECV NAME",
    "RECVID NO",
    "TRACE NUM",
    "BATCH ID",
    "IND NAME",
    "SEC CODE",
    "TRACE NO",
    "ADDENDA",
    "COMP ID",
    "CUST ID",
    "ORIG ID",
    "CO EFF",
    "ORIGIN",
    "REMARK",
    "DATE",
    "DESC",
    "INDN",
    "SETT",
    "TIME",
    "BLK",
    "BNF",
    "SEC",
]


INLINE_KEYS = ["PAYMENT DATE", "ID", "AC"]

if __name__=='__main__':
    
    print(sorted(KEYS,key=len,reverse=True))
    pass