# ACH Keys
KEYS = ['INDIVIDUAL OR RECEIVING COMPANY NAME', 'ORIGINATING BANK NAME', 'EFFECTIVE ENTRY DATE', 'DISCRETIONARY DATA', 'TRANSACTION REF NO', 'ENTRY DESCRIPTION', 'RECEIVER ACCT NUM', 'TRANSACTION CODE', 'RECEIVER ABA NUM', 'SENDING CO NAME', 'TRANSACTION REF', 'EFFECTIVE DATE', 'BANK TRACE NUM', 'CO DISCR DATA', 'INDIVIDUAL ID', 'RECEIVER NAME', 'RETURN REASON', 'TRACE NUMBER', 'COMPANY NAME', 'ORIG CO NAME', 'COMPANY DATA', 'ENTRY DESC R', 'DESCRIPTION', 'BATCH DISCR', 'ENTRY DESCR', 'ENTRY CLASS', 'TRANS TYPE', 'COMPANY ID', 'ITEM TRACE', 'FED REF NO', 'RETURN REF', 'ENTRY DATE', 'IND I D NO', 'ORIG BA NK', 'RECVID NO', 'RECV NAME', 'COMP NAME', 'TRACE NUM', 'CUST NAME', 'IND ID NO', 'DESC DATE', 'ORIG BANK', 'FILE NAME', 'SEC CODE', 'BATCH ID', 'TRACE NO', 'IND NAME', 'ADDENDA', 'COMP ID', 'CUST ID', 'ORIG ID', 'ORIG ID', 'ORIGIN', 'CO EFF', 'REMARK', 'DESC', 'DATE', 'TIME', 'INDN', 'SEC', 'BLK']


INLINE_KEYS = ["PAYMENT DATE", "ID", "AC"]

if __name__=='__main__':
    
    print(sorted(KEYS,key=len,reverse=True))
    pass