# ACH Keys
KEYS = [
    "TRANS TYPE",
    "SENDING CO. NAME",
    "CO. DISCR. DATA",
    "COMPANY ID",
    "DESCRIPTION",
    "EFFECTIVE DATE",
    "ADDENDA",
    "RECV.ID NO",
    "RECV. NAME",
    "DISCRETIONARY DATA",
    "TRACE NUMBER",
    "ENTRY DESCRIPTION",
    "COMPANY NAME",
    "SEC CODE",
    "INDIVIDUAL OR RECEIVING COMPANY NAME",
    "ORIGINATING BANK NAME",
    "INDIVIDUAL ID",
    "EFFECTIVE ENTRY DATE",
    "ITEM TRACE",
    "TRANSACTION CODE",
    "TRANSACTION REF. NO",
    "FED. REF. NO.",
    "RECEIVER NAME",
    "DESC",
    "COMP NAME",
    "COMP ID",
    "SEC",
    "BATCH ID",
    "RECEIVER ACCT NUM",
    "TRANSACTION REF",
    "RECEIVER ABA NUM",
    "TRACE NUM",
    "BANK TRACE NUM",
    "RETURN REASON",
    "RETURN REF",
    "CUST ID",
    "CUST NAME",
    "DATE",
    "TIME",
    "BATCH DISCR",
    "ORIG CO NAME",
    "ORIG ID",
    "ENTRY DESCR",
    "ENTRY CLASS",
    "TRACE NO",
    "ENTRY DATE",
    "IND ID NO",
    "IND NAME",
    "DESC DATE",
    "ORIG BANK",
    "FILE NAME",
    "COMPANY DATA",
    "REMA RK",
    "ORIGIN",
    "CO EFF",
    "REMARK",
    "BLK",
    "ENTRY DESC R",
    "IND I D NO",
    "ORIG BA NK",
    "ORIG ID",
    "INDN",
]

INLINE_KEYS = ["PAYMENT DATE", "ID", "AC"]
