# SWIFT Keys

KEYS = [
    "RECEIVER FINANCIAL INSTITUTION ID",
    "SENDER FINANCIAL INSTITUTION ID",
    "INITIATING PARTY ORG ID",
    "REMITTANCE INFORMATION",
    "DATE/TIME COMPLETED",
    "INSTRUCTED AMOUNT",
    "INSTRUCTING AGENT",
    "SENDERS REFERENCE",
    "ALOK HEMANT SIDD",
    "INSTRUCTED AGENT",
    "RECEIVER ACCOUNT",
    "RECEIVER ADDRESS",
    "CHARGING OPTION",
    "PAYMENT DETAILS",
    "SENDER BANK REF",
    "CONTROL NUMBER",
    "CREDITOR AGENT",
    "FULL REFERENCE",
    "RECEIVING BANK",
    "SENDER ACCOUNT",
    "SENDER ADDRESS",
    "RECEIVER NAME",
    "WIRE CURRENCY",
    "CREDITOR REF",
    "DEBTOR AGENT",
    "INITIATED BY",
    "APPROVED BY",
    "BENEFICIARY",
    "FEES LIFTED",
    "RELATED REF",
    "SENDER NAME",
    "WIRE AMOUNT",
    "ORIGINATOR",
    "PAR NUMBER",
    "PARTIALREF",
    "SENDER REF",
    "VALUE DATE",
    "INSTG BNK",
    "RECV BANK",
    "SWIFT REF",
    "WIRE TYPE",
    "CREDITOR",
    "FED IMAD",
    "AMT/CUR",
    "BENEBNK",
    "FED REF",
    "ORG BNK",
    "RECV BK",
    "SND BNK",
    "BNF BK",
    "CR BNK",
    "DB BNK",
    "DEBTOR",
    "DR BNK",
    "INT BK",
    "SOURCE",
    "ADDR",
    "CTRY",
    "DATE",
    "IMAD",
    "ORIG",
    "RATE",
    "S AC",
    "TIME",
    "UETR",
    "ABA",
    "BBI",
    "BNF",
    "CTY",
    "IBK",
    "OBI",
    "RFB",
    "TCN",
    "TRN",
]


INLINE_KEYS = ["ID","PURPOSE CODE","PURPOSE","AC","AC"]

if __name__=='__main__':
    
    print(sorted(KEYS,key=len,reverse=True))
    pass