# SWIFT Keys

KEYS = ['RECEIVER FINANCIAL INSTITUTION ID', 'SENDER FINANCIAL INSTITUTION ID', 'INITIATING PARTY ORG ID', 'REMITTANCE INFORMATION', 'DATE/TIME COMPLETED', 'INSTRUCTED AMOUNT', 'SENDERS REFERENCE', 'INSTRUCTING AGENT', 'RECEIVER ACCOUNT', 'RECEIVER ADDRESS', 'INSTRUCTED AGENT', 'CHARGING OPTION', 'PAYMENT DETAILS', 'SENDER BANK REF', 'RECEIVING BANK', 'CREDITOR AGENT', 'CONTROL NUMBER', 'SENDER ACCOUNT', 'SENDER ADDRESS', 'FULL REFERENCE', 'WIRE CURRENCY', 'RECEIVER NAME', 'DEBTOR AGENT', 'CREDITOR REF', 'INITIATED BY', 'WIRE AMOUNT', 'FEES LIFTED', 'APPROVED BY', 'RELATED REF', 'SENDER NAME', 'BENEFICIARY', 'PAR NUMBER', 'VALUE DATE', 'SENDER REF', 'ORIGINATOR', 'PARTIALREF', 'SWIFT REF', 'WIRE TYPE', 'RECV BANK', 'CREDITOR', 'FED IMAD', 'RECV BK', 'BENEBNK', 'AMT/CUR', 'SND BNK', 'ORG BNK', 'FED REF', 'DEBTOR', 'SOURCE', 'BNF BK', 'INT BK', 'UETR', 'IMAD', 'DATE', 'TIME', 'ORIG', 'RATE', 'S AC', 'TRN', 'BNF', 'ABA', 'RFB', 'TCN', 'OBI', 'BBI']


INLINE_KEYS = ["ID","PURPOSE CODE","PURPOSE","AC","AC"]

if __name__=='__main__':
    
    print(sorted(KEYS,key=len,reverse=True))
    pass