# SWIFT Keys

KEYS = [
    "PAR NUMBER","SWIFT REF","DATE/TIME COMPLETED","VALUE DATE","WIRE CURRENCY","WIRE AMOUNT","INSTRUCTED AMOUNT","SENDERS REFERENCE","DEBTOR","DEBTOR AGENT","INSTRUCTING AGENT","RECEIVING BANK","CREDITOR","CREDITOR REF","REMITTANCE INFORMATION","CREDITOR AGENT","FEES LIFTED","UETR","CHARGING OPTION","IMAD","SOURCE","CONTROL NUMBER","INITIATED BY","APPROVED BY","WIRE TYPE","DATE", "TIME","TRN","FED IMAD","RELATED REF","ORIG","BNF","BNF BK","INT BK","RECV BK","PAYMENT DETAILS","SENDER BANK REF","SENDER REF","SENDER NAME","SENDER ACCOUNT","SENDER FINANCIAL INSTITUTION ID","SENDER ADDRESS","RECEIVER NAME","RECEIVER ACCOUNT","RECEIVER FINANCIAL INSTITUTION ID","RECEIVER ADDRESS","ORIGINATOR","BENEFICIARY","BENEBNK","ABA","RFB","AMT/CUR","RATE","TCN","OBI","BBI","FULL REFERENCE","PARTIALREF","SND BNK","S AC","ORG BNK","INITIATING PARTY ORG ID","FED REF","RECV BANK","INSTRUCTED AGENT"
]

INLINE_KEYS = ["ID","PURPOSE CODE","PURPOSE","AC","AC"]