# WIRE KEYS

KEYS = ['TRANSACTION REF NO', 'TRANSACTION REF NO', 'PAYMENT DETAILS', 'EXCHANGE AMOUNT', 'FULL REFERENCE', 'BBKBENEFICIARY', 'ORIG BANK ABA', 'CURRENCY DESC', 'EXCHANGE RATE', 'FED REF NO', 'REC BANK ABA', 'PAYMENT/PURP', 'BBKCUST NAME', 'RECEIVED AT', 'COMM CHARGE', 'SERVICE REF', 'RELATED REF', 'VALUE DATE', 'ORIGINATOR', 'USD AMOUNT', 'PARTIALREF', 'ACCT PARTY', 'ORIG BANK', 'REFERENCE', 'WIRE TYPE', 'SENDER AC', 'RECV BANK', 'REC BANK', 'FED IMAD', 'SNDR REF', 'YOUR REF', 'SND BNK', 'BENEBNK', 'SENT AT', 'FED REF', 'RECV BK', 'ACCOUNT', 'PAID TO', 'REF NO', 'ORG BK', 'SND BK', 'BNF BK', 'AMOUNT', 'FED ID', 'REMARK', 'INT BK', 'INS BK', 'ORIG', 'BN F', 'TIME', 'DATE', 'UETR', 'INFO', 'TYPE', 'ORG', 'OGB', 'BNF', 'TTM', 'LTN', 'TRN', 'REF', 'OBI', 'TYP', 'SRC', 'SBR', 'RFB', 'ABA', 'BIC', 'IBK', 'SBK', 'OBK', 'POB', 'QID', 'DOB', 'BBI', 'SRF', 'BBI', 'BBK', 'BC']


INLINE_KEYS = ["AC", "ID"]

if __name__=='__main__':
    
    # print(sorted(KEYS,key=len,reverse=True))
    pass