# WIRE KEYS.

KEYS = [
    "FULL REFERENCE", "PAYMENT DETAILS", "VALUE DATE",
    "ORIG BANK ABA", "REC BANK ABA", "ORIG BANK", "REC BANK",
    "ORIG", "ORG", "ORIGINATOR", "ORG BK", "OGB",
    "SND BK", "SND BNK","BBK"
    "BENEFICIARY", "BNF", "BNF BK", "BENEBNK", "BN F",
    "RECEIVED AT", "SENT AT", "TTM", "TIME", "DATE",
    "AMOUNT", "USD AMOUNT", "CURRENCY DESC", "EXCHANGE AMOUNT",
    "EXCHANGE RATE", "COMM CHARGE",
    "FED REF", "FED IMAD", "FED ID", "LTN", "TRN", "UETR",
    "SNDR REF", "SERVICE REF", "RELATED REF", "REFERENCE",
    "REF", "PARTIALREF", "RECV BK",
    "OBI", "PAYMENT/PURP", "REMARK", "INFO",
    "TYP", "TYPE", "WIRE TYPE",
    "SRC", "SBR", "INT BK", "INS BK",
    "ACCT PARTY", "ACCOUNT","RFB", "ABA", "BIC" , "IBK","BC",'YOUR REF','PAID TO','SBK','OBK','POB','QID','DOB','BBI',"SENDER AC","REF NO.","SRF","RECV BANK","BBK"
    "CUST NAME",
    "BBI",
    "BBK",
]

INLINE_KEYS = ["AC", "ID"]
