# WIRE KEYS

KEYS = [
    "TRANSACTION REF NO",
    "EXCHANGE AMOUNT",
    "PAYMENT DETAILS",
    "BBKBENEFICIARY",
    "FULL REFERENCE",
    "CURRENCY DESC",
    "EXCHANGE RATE",
    "ORIG BANK ABA",
    "BBKCUST NAME",
    "PAYMENT/PURP",
    "REC BANK ABA",
    "COMM CHARGE",
    "RECEIVED AT",
    "RELATED REF",
    "SERVICE REF",
    "ACCT PARTY",
    "FED REF NO",
    "ORIGINATOR",
    "PARTIALREF",
    "USD AMOUNT",
    "VALUE DATE",
    "ORIG BANK",
    "RECV BANK",
    "REFERENCE",
    "SENDER AC",
    "WIRE TYPE",
    "FED IMAD",
    "REC BANK",
    "SNDR REF",
    "YOUR REF",
    "ACCOUNT",
    "BENEBNK",
    "FED REF",
    "PAID TO",
    "RECV BK",
    "SENT AT",
    "SND BNK",
    "AMOUNT",
    "BNF BK",
    "FED ID",
    "INS BK",
    "INT BK",
    "ORG BK",
    "REF NO",
    "REMARK",
    "SND BK",
    "BN F",
    "DATE",
    "INFO",
    "ORIG",
    "TIME",
    "TYPE",
    "UETR",
    "ABA",
    "BBI",
    "BBK",
    "BIC",
    "BNF",
    "DOB",
    "IBK",
    "LTN",
    "OBI",
    "OBK",
    "OGB",
    "ORG",
    "POB",
    "QID",
    "REF",
    "RFB",
    "SBK",
    "SBR",
    "SRC",
    "SRF",
    "TRN",
    "TTM",
    "TYP",
    "BC",
]


INLINE_KEYS = ["AC", "ID"]

if __name__=='__main__':
    print(sorted(KEYS,key=len,reverse=True))
    pass